<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Playwright" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ComputerUse.Core\ComputerUse.Core.csproj" />
    <ProjectReference Include="..\ComputerUse.Playwright\ComputerUse.Playwright.csproj" />
    <ProjectReference Include="..\ComputerUse.Replay\ComputerUse.Replay.csproj" />
  </ItemGroup>
</Project>
